'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServicioDatos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.webserviceserver.somee.com/", ConfigurationName:="ServicioDatos.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/BuscaRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuscaRegistro(ByVal cadena As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/BuscaRegistro", ReplyAction:="*")>  _
        Function BuscaRegistroAsync(ByVal cadena As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/NuevoRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function NuevoRegistro(ByVal NOMBRE As String, ByVal TELEFONO As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/NuevoRegistro", ReplyAction:="*")>  _
        Function NuevoRegistroAsync(ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/ActualizarRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActualizarRegistro(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/ActualizarRegistro", ReplyAction:="*")>  _
        Function ActualizarRegistroAsync(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/EliminaRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminaRegistro(ByVal ID As Integer) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceserver.somee.com/EliminaRegistro", ReplyAction:="*")>  _
        Function EliminaRegistroAsync(ByVal ID As Integer) As System.Threading.Tasks.Task(Of Object)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServicioDatos.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioDatos.WebService1Soap)
        Implements ServicioDatos.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function BuscaRegistro(ByVal cadena As String) As System.Data.DataSet Implements ServicioDatos.WebService1Soap.BuscaRegistro
            Return MyBase.Channel.BuscaRegistro(cadena)
        End Function
        
        Public Function BuscaRegistroAsync(ByVal cadena As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServicioDatos.WebService1Soap.BuscaRegistroAsync
            Return MyBase.Channel.BuscaRegistroAsync(cadena)
        End Function
        
        Public Function NuevoRegistro(ByVal NOMBRE As String, ByVal TELEFONO As String) As Object Implements ServicioDatos.WebService1Soap.NuevoRegistro
            Return MyBase.Channel.NuevoRegistro(NOMBRE, TELEFONO)
        End Function
        
        Public Function NuevoRegistroAsync(ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object) Implements ServicioDatos.WebService1Soap.NuevoRegistroAsync
            Return MyBase.Channel.NuevoRegistroAsync(NOMBRE, TELEFONO)
        End Function
        
        Public Function ActualizarRegistro(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As Object Implements ServicioDatos.WebService1Soap.ActualizarRegistro
            Return MyBase.Channel.ActualizarRegistro(ID, NOMBRE, TELEFONO)
        End Function
        
        Public Function ActualizarRegistroAsync(ByVal ID As Integer, ByVal NOMBRE As String, ByVal TELEFONO As String) As System.Threading.Tasks.Task(Of Object) Implements ServicioDatos.WebService1Soap.ActualizarRegistroAsync
            Return MyBase.Channel.ActualizarRegistroAsync(ID, NOMBRE, TELEFONO)
        End Function
        
        Public Function EliminaRegistro(ByVal ID As Integer) As Object Implements ServicioDatos.WebService1Soap.EliminaRegistro
            Return MyBase.Channel.EliminaRegistro(ID)
        End Function
        
        Public Function EliminaRegistroAsync(ByVal ID As Integer) As System.Threading.Tasks.Task(Of Object) Implements ServicioDatos.WebService1Soap.EliminaRegistroAsync
            Return MyBase.Channel.EliminaRegistroAsync(ID)
        End Function
    End Class
End Namespace
